version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s'
  json:
    format: '{"time": "%(asctime)s", "level": "%(levelname)s", "name": "%(name)s", "module": "%(module)s", "function": "%(funcName)s", "message": "%(message)s"}'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: ./logs/app.log
    maxBytes: 10485760  # 10MB log file size limit
    backupCount: 5      # Keep 5 backups of the log files
    encoding: utf8

  json_file:
    class: logging.FileHandler
    level: INFO
    formatter: json
    filename: ./logs/app_json.log
    encoding: utf8

loggers:
  my_logger:
    level: DEBUG
    handlers: [console, file, json_file]
    propagate: no

root:
  level: WARNING
  handlers: [console]

